[platformio]
default_envs = node
src_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
build_flags =
  -I shared/include

[env:brain]
board = m5stack-atom
lib_deps =
  m5stack/M5Atom
  fastled/FastLED
build_src_filter =
  -<*>
  +<apps/brain/src/>

[env:node]
board = m5stack-atom
lib_deps =
  fastled/FastLED
build_src_filter =
  -<*>
  +<apps/node/src/>
